import numpy as np
import pandas as pd

def filter_dssp(df, alphafold_dssp_results, uniprot_col = "uniprot", trembl_col = "trembl", seq_col = "sequence",
                verbose = False):
    '''
    Removes Ensembl transmembrane domains from scannable protein sequences

    Args:
        df (pd.DataFrame):             input dataframe containing sequences to sanitize
        alphafold_dssp_results (dict): AlphaDSSP lookup dict generated by alphadssp.generate_dssp()
        uniprot_col (str):             column name in df containing UniProt/SwissProt IDs
        trembl_col (str):              column name in df containing UniProt/TrEMBL IDs
        seq_col (str):                 column name in df containing protein sequences
        verbose (bool):                whether to display messages

    Returns:
        df (pd.DataFrame):             modified input dataframe
    '''

    df = df.copy()

    if "forbidden_secondary_structure" not in df.columns:
        df["forbidden_secondary_structure"] = None
        fss_col_existed = False
    else:
        fss_col_existed = True

    match_count = 0
    mismatch_count = 0
    for idx in df.index:
        uniprot_id = df.at[idx, uniprot_col]
        uniprot_id = uniprot_id if isinstance(uniprot_id, str) else ""
        trembl_id = df.at[idx, trembl_col]
        trembl_id = trembl_id if isinstance(trembl_id, str) else ""

        lookup_id = uniprot_id if len(uniprot_id) > 0 else trembl_id
        if len(lookup_id) > 0:
            dssp_results = alphafold_dssp_results.get(lookup_id)
            protein_seq = df.at[idx, seq_col]
            if dssp_results is not None:
                forbidden_mask = dssp_results[0]
                existing_val = df.at[idx, "forbidden_secondary_structure"]

                same_length = len(forbidden_mask) == len(protein_seq) if isinstance(protein_seq, str) else False
                if same_length:
                    match_count += 1
                    if not fss_col_existed or existing_val is None:
                        df.at[idx, "forbidden_secondary_structure"] = forbidden_mask
                    elif isinstance(df.at[idx, "forbidden_secondary_structure"], np.ndarray):
                        df.at[idx, "forbidden_secondary_structure"] = np.logical_or(existing_val, forbidden_mask)
                    else:
                        raise Exception(f"df has forbidden_secondary_structure col, but is not np.ndarray (value={existing_val}, type={type(existing_val)})")
                else:
                    mismatch_count += 1

    print(f"During Alphafold DSSP secondary structure filtering, {mismatch_count} length mismatches were encountered "
          f"({100*mismatch_count/(mismatch_count+match_count):.2f}%)") if verbose else None

    return df